### ISSUE TITLE
Breaks hashchange event if bound to window

### ISSUE THREAD

**Issue by RyanEwen** [afklondon/jquery.inactivity#1]
I just noticed that hashchange events no longer make it to my application if I initialize the plugin on 'window'.

It seems to be okay when using 'document', though.

**Comment by RyanEwen** [comment]
Scratch that, seems to happen on 'document' as well. 

I've looked through the source code and don't see any obvious reason for it

**Comment by RyanEwen** [comment]
Hmm it seems to break jquery draggable when on `document` now.

**Comment by RyanEwen** [comment]
To clarify the issue, draggables will work once, and then stop working after that, but only when jquery.inactivity is present.

After more investigation it seems to be due to your `clear` function being called. If I remove that, it works fine. So then I added it back and added a namespace to each event name, but surprisingly this doesn't help.

**Comment by RyanEwen** [comment]
Figured out the exact cause. If no custom event names are specified then `clear` unbinds all events by mistake. I am going to make a fork and fix this.

**Comment by kaparelos** [comment]
Thanks for reporting and fixing :)
